### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by IngwiePhoenix** [progschj/ThreadPool#13]
Hey.

So I see that this library uses C++11 heavily. How much is this supported on Windows? I want to use this for a cross-platform project.

Kind regards,
Ingwie

**Comment by progschj** [comment]
From what I remember it compiles and runs the example in MSVC2013. But that is about as far as my Windows testing goes.

**Comment by IngwiePhoenix** [comment]
Okay, thank you! :)
