### ISSUE TITLE
android and ios support?

### ISSUE THREAD

**Issue by ghostincircuit** [progschj/ThreadPool#17]
I tried to compile this using android NDK r10 with no luck. There seems to be something wrong with std::future, have you tried or plan to use it on mobile platform?

**Comment by progschj** [comment]
I haven't tried it myself. Can you post the errors?

**Comment by rubixcubin** [comment]
Hey ghostincircuit 
Take a look at this:

Try setting the toolchain version to 
NDK_TOOLCHAIN_VERSION := clang
and set flags to -std=c++11
LOCAL_CPPFLAGS += -std=c++11

Reference: http://stackoverflow.com/questions/17616915/c11-stdasync-in-android-ndk-does-not-work

**Comment by ghostincircuit** [comment]
thanks rubixcubin, it works both on ios and android.
clang it not necessary, gcc4.8 is also ok, but I need to use APP_STL := c++_static, I tried gnustl but cannot pass compilation.
