### ISSUE TITLE
Race Condition in ThreadPool Constructor

### ISSUE THREAD

**Issue by thejacobpollack** [progschj/ThreadPool#23]
There's a race condition for the shared resource `task` in the `ThreadPool` constructor. Move the variable definition outside of the infinite loop and add the C++11 `thread_local` storage duration specifier:

``` C++
thread_local std::function<void()> task;
```

**Comment by progschj** [comment]
The task object is local to the lambda (and hence the thread) so no other thread even knows about it. So I'm fairly sure it is fine as it is.

**Comment by thejacobpollack** [comment]
You're absolutely right -- I overlooked that. I apologize.
