### ISSUE TITLE
How can We USE A FUNCTION INSIDE YOUR CODE??

### ISSUE THREAD

**Issue by hanito** [progschj/ThreadPool#29]
How can we add a function inside your code. IT's totally unclear

**Comment by wilx** [comment]
What do you mean? The [`example.cpp`](https://github.com/progschj/ThreadPool/blob/master/example.cpp) shows hot to use the thread pool.

**Comment by progschj** [comment]
This should do it i think:

```
int foo(float x) { return x; }
//...
future<int> result = pool.enqueue(foo, 3.14f); 
```

**Comment by hanito** [comment]
yes Prog I coded it before. For a class I should do the following:
IF i have a function bar in a class
int foo::bar(float x) { return x; }
//...
future<int> result = pool.enqueue(&foo::bar, this, 3.14f);
