### ISSUE TITLE
why need to return when (this->stop && this->tasks.empty())

### ISSUE THREAD

**Issue by yinchunxiang** [progschj/ThreadPool#33]
Can we just return when this->stop is true

**Comment by progschj** [comment]
In the long gone past this was actually how the first version worked. It changes the behaviour though. Back then I got lots of emails about how the pool wouldn't "finish his work" if it was destroyed. That can be sensible behaviour but probably shouldn't be the default. Without the emptiness check there could be enqueued tasks that get never executed... (and as a result futures that would just block indefinitely if waited on).

**Comment by Darelbi** [comment]
what about using a thread for "closing the pool finally once it is destroyed" ?

**Comment by yinchunxiang** [comment]
Got it, thanks :)
