### ISSUE TITLE
enqueue: capture by universal reference

### ISSUE THREAD

**Issue by daniel-j-h** [progschj/ThreadPool#5]
Is there a reason the enqueue function doesn't capture the type-deduced function as universal reference? E.g.:

``` c++
template<typename Function>
auto enqueue(Function&& f) -> std::future<decltype(std::forward<F>(f)())>;
```

This would allows us to std::forward(f) later on, preserving the rvalue/lvalue type.

This should handle situations nicely where we enqueue
- rvalues (e.g. anonymous lambdas)
- lvalues (e.g. named functors)

**Comment by progschj** [comment]
Sorry for the lat answer, I was stuck in the military for a few weeks...
The only reason is my still limited knowledge of C++11 ;). I incorporated this in the develop branch.
