### ISSUE TITLE
你他妈个臭傻逼

### ISSUE THREAD

**Issue by dongwencai** [progschj/ThreadPool#60]

**Comment by wilx** [comment]
Try again in English, please.

**Comment by aorandexiaohai** [comment]
You mother is a smelly SB.

**Comment by liyang-lomo** [comment]
This threadpool is so simple and elegant, it is a good learning material, I don’t know why it’s so embarrassing, it’s estimated that Tencent games are playing more.

**Comment by aorandexiaohai** [comment]
You can you up, no bb please.

**Comment by aorandexiaohai** [comment]
You can say that cpp is a shit comparing with other languages, why do you use it?

**Comment by liyang-lomo** [comment]
> You can say that cpp is a shit comparing with other languages, why do you use it?

I think you misunderstood what I meant.

**Comment by progschj** [comment]
I have no clue what this is about so I'm going to close it as being off topic.

**Comment by Naville** [comment]
@progschj Some cursing and f-words in Chinese. Shame. You might want to block him though
