### ISSUE TITLE
pull request，add volatile

### ISSUE THREAD

**Issue by uxctx** [progschj/ThreadPool#62]
`  line:30    bool stop;`   => `	volatile bool stop;`

**Comment by wilx** [comment]
[**@lucpp**](https://github.com/lucpp) commented on [24 Oct 2018, 11:25 CEST](https://github.com/progschj/ThreadPool/issues/62#issue-373387400 "2018-10-24T09:25:49Z - Replied by Github Reply Comments"):
> `  line:30    bool stop;`   =&gt; `	volatile bool stop;`

That is not necessary. The `stop` variable is only accessed with held `queue_mutex`.

**Comment by fogti** [comment]
@wilx I agree.
