### ISSUE TITLE
queue<packaged_task> has memory leaks?

### ISSUE THREAD

**Issue by regomne** [progschj/ThreadPool#65]
When I enqueue some task:

```
		for (int i = 0; i < 10000; i++)
		{
			pool.enqueue_task([i] {
				cout << i << endl;
			});
		}
```
		
After all the task ENDED:

![snipaste_2018-12-11_11-35-45](https://user-images.githubusercontent.com/5319433/49776879-f67a3480-fd38-11e8-9807-ad2e6f31ff35.png)

The std::packaged_task don't seem to be released, and they will be released after ThreadPool destructed. The same to queue<function>.

**Comment by wilx** [comment]
The queue keeps the storage but the tasks themselves get destroyed after they are done.

**Comment by regomne** [comment]
Thanks, I replaced queue with deque and use its shrink_to_fit to reduce memory .
