### ISSUE TITLE
What does the following code means?

### ISSUE THREAD

**Issue by hongyx11** [progschj/ThreadPool#68]
auto ThreadPool::enqueue(F&& f, Args&&... args)
-> std::future<typename std::result_of<F(Args...)>::type>

in Threadpool.h, what does array(->) means? return value?

https://github.com/progschj/ThreadPool/blob/master/ThreadPool.h#L19

Thank you very much

**Comment by GeraldLee** [comment]
you could find answer here https://stackoverflow.com/questions/22514855/arrow-operator-in-function-heading

**Comment by GeraldLee** [comment]
> auto ThreadPool::enqueue(F&& f, Args&&... args)
> -> std::future<typename std::result_of<F(Args...)>::type>
> 
> in Threadpool.h, what does array(->) means? return value?
> 
> https://github.com/progschj/ThreadPool/blob/master/ThreadPool.h#L19
> 
> Thank you very much

you could find answer here https://stackoverflow.com/questions/22514855/arrow-operator-in-function-heading

**Comment by hongyx11** [comment]
Thank you very much.
