### ISSUE TITLE
Duplicate symbol

### ISSUE THREAD

**Issue by iliocatallo** [progschj/ThreadPool#7]
Hi,

If I try to include ThreadPool.h in in different source files in my project, the linker starts complaining about duplicate symbols. I'm using XCode 4.6.1 (clang 4.2).

Thanks.

**Comment by progschj** [comment]
I assume all the nontemplate members need to be put in a cpp file for that to work. Alternatively we could think of an excuse to make ThreadPool a template itself :D (like having a scheduling policy parameter).

**Comment by iliocatallo** [comment]
So, if I got it right, it is sufficient to move all non-tempalate members in a hypothetical ThreadPool.cpp file. I'll try ASAP ;)

**Comment by progschj** [comment]
I fixed this on the develop branch by declaring the nontemplates inline.
