### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by link-duan** [progschj/ThreadPool#73]
thread_pool.h:22:10: error: ‘std::future<typename std::result_of<_Functor(_ArgTypes ...)>::type> ThreadPool::enqueue(F&&, Args&& ...) [with F = main(int, char**)::<lambda()>; Args = {}; typename std::result_of<_Functor(_ArgTypes ...)>::type = void]’, declared using local type ‘main(int, char**)::<lambda()>’, is used but never defined [-fpermissive]
     auto enqueue(F &&f, Args &&... args)
          ^~~~~~~

**Comment by peakjun** [comment]
how to resolve it ?
