### ISSUE TITLE
Can you update this implementation to C++17?

### ISSUE THREAD

**Issue by fotolist** [progschj/ThreadPool#78]
The std::"result_of" is deprecated in C++ 17. Can you update this to a new version? Thank you.

**Comment by supercairos** [comment]
I've fixed it here :
https://gist.github.com/supercairos/2893684c639610f04f67658780182c8b

**Comment by adarshpandey** [comment]
> I've fixed it here :
> https://gist.github.com/supercairos/2893684c639610f04f67658780182c8b

hey @supercairos ,
Im new to github.I visited the link you provided which shows the link to file Threadpool.h
But, could you tell me how to know the fix,I mean which file/repo to take diff from..?

**Comment by fotolist** [comment]
> I've fixed it here :
> https://gist.github.com/supercairos/2893684c639610f04f67658780182c8b

Thank you so much.
