### ISSUE TITLE
What will be the appropriate value for a pool size?

### ISSUE THREAD

**Issue by anuragvohraec** [progschj/ThreadPool#82]
Hi,

Can any one suggest me how to select an appropriate pool_size value ?
```c++
ThreadPool pool(pool_size);
```
WIll it be equivalent to number of CPU cores on the system ? Or can be greater than it too ?

How do you select it?
Specifically if code is supposed to run on different systems?

**Comment by abbaswasim** [comment]
I would do something something like the following?

`ThreadPool pool(std::max(1, std::thread::hardware_concurrency() - 1));`

**Comment by anuragvohraec** [comment]
> I would do something something like the following?
> 
> `ThreadPool pool(std::max(1, std::thread::hardware_concurrency() - 1));`

Why -1 from concurrent thread supported, any specific reason ?

**Comment by abbaswasim** [comment]
To leave a thread or more (-2, -3) for other stuff that might be required to run. Of course you don't need to be that nice. If you don't the OS will still make sure other things run of course but that might not be ideal.
